import { getBrowserSourcePages } from '../storage/browserSources'
import { loadLibrarySources } from '../library/sourceLibrary'
import { getLessonBrief, getLessonPlan } from '../lesson/lessonPlans'
import { recordScopeReview, type ScopeReviewInput } from '../lesson/lessonScope'
import { closeSourceInspection, inspectSourcePage, inspectSourcePages } from '../reader/sourceInspectionBridge'
import { navigatePrism, sourcePath, lessonPath } from '../navigation'
import { getLessonDocumentByPlan } from '../lesson/lessonDocuments'
import { agentContentAllowed, AGENT_ACCESS_REFUSAL, refusalResult, sourceEvidenceResult, textResult } from './context'
import { useModelContextTool } from './useModelContextTool'
import { getAuthoringGuide } from './authoringGuide'
import { compactSourcePacket, readSourcePacket } from '../storage/sourcePackets'
import { readAuthoringWorkspace } from './authoringWorkspace'
import { importGeneratedIllustration } from '../storage/lessonIllustrations'
import { cropSchema, normalizeVisualRequest } from './sourceVisualRequest'
import { paginationSchema } from './toolPagination'
import { withCurrentSourceAccess } from './sourceAccess'

const sourceId = { type: 'string' }
const pageNumber = { type: 'integer', minimum: 1 }

export function useDocumentIntelligenceTools() {
  useModelContextTool({ name: 'get_authoring_workspace', description: 'Discover saved briefs/plans for a source, read focused brief/plan/review views, or resume an explicit saved assignment with readiness, review gaps, draft version and next calls. Follow exact next_call pagination. Saved-work reads require source access; this tool never selects an assignment or approves work.', readOnly: true,
    inputSchema: { type: 'object', properties: { view: { type: 'string', enum: ['resume', 'discovery', 'brief', 'plan', 'reviews'], description: 'Default resume requires saved brief_id or plan_id. Discovery requires source_id and lists briefs or plans without choosing one. Focused views return only requested details.' }, source_id: sourceId, kind: { type: 'string', enum: ['briefs', 'plans'], description: 'Discovery only; defaults to briefs.' }, part: { type: 'string', enum: ['sections', 'coverage', 'ranges', 'objectives', 'questions'], description: 'Plan view only; defaults to sections.' }, brief_id: sourceId, plan_id: sourceId, section_id: sourceId, review_cursor: { type: 'integer', minimum: 0, description: 'Resume only. Other views use cursor from next_call.' }, ...paginationSchema }, additionalProperties: false },
    execute: async args => {
      try { return sourceEvidenceResult(await readAuthoringWorkspace(args), 48_000) }
      catch (cause) { return refusalResult(cause instanceof Error ? cause.message : 'Could not resume this authoring workspace.') }
    },
  })
  useModelContextTool({ name: 'get_source_visual_catalog', description: 'Find candidate figure regions and captions on selected pages, up to four pages per call. Follow next_call and pass relevant suggested_view objects to inspect_source_visual with action: open. Requires image access. Bounds and captions are heuristic; verify pixels before reuse. No OCR or numeric chart extraction.', readOnly: true,
    inputSchema: { type: 'object', properties: { source_id: sourceId, page_start: pageNumber, page_end: pageNumber, cursor: pageNumber }, required: ['source_id', 'page_start', 'page_end'], additionalProperties: false },
    execute: async args => {
      const source = await accessibleSource(args.source_id)
      if (!source) return refusalResult(AGENT_ACCESS_REFUSAL)
      if (!['open_license', 'public_domain'].includes(source.rights_status) && !source.agent_visual_granted) return refusalResult('Enable source access including page images in the visible source overview first. Older text-only grants do not include visual access.')
      try {
        const { getSourceVisualCatalog } = await import('../reader/sourceVisualCatalog')
        return sourceEvidenceResult(await getSourceVisualCatalog(source.id, Number(args.page_start), Number(args.page_end), source.page_count ?? 0, args.cursor === undefined ? undefined : Number(args.cursor)), 48_000)
      } catch (cause) { return refusalResult(cause instanceof Error ? cause.message : 'Could not catalog these visuals. Inspect the original pages with inspect_source_visual.') }
    },
  })
  useModelContextTool({ name: 'import_generated_illustration', description: 'Attach a PNG/JPEG generated by your image tool to this local source. Use only when a spatial or conceptual illustration meaningfully explains the lesson. Supply actual generated image bytes as a data URL, creator/model attribution and explanatory purpose. This never generates an image itself. The renderer always labels it AI-generated; use an illustration block with added_explanation provenance. Never use generated images for original evidence or exact measured charts.',
    inputSchema: { type: 'object', properties: { source_id: sourceId, data_url: { type: 'string', maxLength: 8_400_000 }, attribution: { type: 'string', minLength: 1, maxLength: 600 }, purpose: { type: 'string', minLength: 1, maxLength: 1200 } }, required: ['source_id', 'data_url', 'attribution', 'purpose'], additionalProperties: false },
    execute: async args => {
      if (!await accessibleSource(args.source_id)) return refusalResult(AGENT_ACCESS_REFUSAL)
      return textResult(await importGeneratedIllustration(args as unknown as Parameters<typeof importGeneratedIllustration>[0]))
    },
  })
  useModelContextTool({ name: 'read_source_packet', description: 'Primary evidence reader for lesson authoring. Pass the full requested PDF page range; each bounded response transports up to eight pages of exact indexed text, citations, captions and warnings. Execute next_call unchanged until null. This avoids Reader navigation and page-by-page text scans. Inspect relevant original figures separately with inspect_source_visual and browser vision.', readOnly: true,
    inputSchema: { type: 'object', properties: { source_id: sourceId, page_start: pageNumber, page_end: pageNumber, cursor: { type: 'string' }, include_details: { type: 'boolean', description: 'Include complete page profiles and element confidence, reading order and reasons. Use the same start/end for one page, including scans.' }, format: { type: 'string', enum: ['detailed', 'compact'], description: 'Prefer compact: lossless rows with a shared columns key reduce repeated metadata. Detailed remains available for compatibility.' } }, required: ['source_id', 'page_start', 'page_end'], additionalProperties: false },
    execute: async (args) => {
      const source = await accessibleSource(args.source_id)
      if (!source) return refusalResult(AGENT_ACCESS_REFUSAL)
      try {
        if (args.format !== undefined && args.format !== 'compact' && args.format !== 'detailed') return refusalResult('Choose compact or detailed evidence format.')
        if (args.include_details !== undefined && typeof args.include_details !== 'boolean') return refusalResult('include_details must be a boolean.')
        const packet = await readSourcePacket({ source_id: source.id, page_start: Number(args.page_start), page_end: Number(args.page_end), cursor: typeof args.cursor === 'string' ? args.cursor : undefined, format: args.format, include_details: args.include_details }, source.page_count ?? 0, getBrowserSourcePages)
        return sourceEvidenceResult(await withCurrentSourceAccess(source, args.format === 'compact' ? compactSourcePacket(packet) : packet), 48_000)
      } catch (cause) { return refusalResult(cause instanceof Error ? cause.message : 'Could not read this evidence packet. Retry the same request.') }
    },
  })
  useModelContextTool({ name: 'get_authoring_guide', description: 'Read the concise core contract once before authoring. Request writing, visuals or revisions only when needed; navigation alone needs no authoring guide.', readOnly: true, inputSchema: { type: 'object', properties: { topic: { type: 'string', enum: ['core', 'writing', 'visuals', 'revisions'] } }, additionalProperties: false }, execute: async args => { try { return textResult(getAuthoringGuide(args.topic)) } catch (cause) { return refusalResult(cause instanceof Error ? cause.message : 'Unknown guide topic.') } } })
  useModelContextTool({ name: 'inspect_source_visual', description: 'Open one original PDF page/crop or a contact sheet of 1–4 views for browser vision; close the same viewer with action: close alone. Opening requires image access and returns render metadata after pixels appear. Inspect the pixels before making visual claims.',
    inputSchema: { type: 'object', properties: { action: { type: 'string', enum: ['open', 'close'], description: 'Open requires source_id and either page_number/bbox or views. Close takes action alone and works after access revocation.' }, source_id: sourceId, page_number: pageNumber, bbox: cropSchema, views: { type: 'array', minItems: 1, maxItems: 4, description: 'Batch alternative to page_number/bbox. Select relevant figures or uncertain pages from indexed evidence.', items: { type: 'object', properties: { page_number: pageNumber, bbox: cropSchema }, required: ['page_number'], additionalProperties: false } } }, required: ['action'], additionalProperties: false },
    execute: async (args) => {
      if (args.action === 'close') {
        if (Object.keys(args).some(key => key !== 'action')) return refusalResult('Closing takes action: close alone.')
        closeSourceInspection()
        return textResult({ visible_state: 'source_inspection_closed' })
      }
      if (args.action !== 'open') return refusalResult('Choose action: open or close.')
      const source = await accessibleSource(args.source_id)
      if (!source) return refusalResult(AGENT_ACCESS_REFUSAL)
      if (!['open_license', 'public_domain'].includes(source.rights_status) && !source.agent_visual_granted) return refusalResult('Enable source access including page images in the visible source overview first. Older text-only grants do not include visual access.')
      try {
        const views = normalizeVisualRequest(args, source.page_count ?? 0)
        const result = args.views !== undefined
          ? await inspectSourcePages(source.id, views)
          : await inspectSourcePage(source.id, views[0].page_number, views[0].bbox)
        return sourceEvidenceResult(result)
      } catch (cause) { return refusalResult(cause instanceof Error ? cause.message : 'Could not open the selected visuals.') }
    },
  })
  useModelContextTool({ name: 'record_scope_review', description: 'Save a resumable review of 1–8 source pages for a lesson brief. Preserve key claims, methods, qualifications, examples, figure findings, and essential anchors. These are agent-authored notes, not independently verified fidelity. For long synthesis, review the complete requested range before propose_lesson_plan with coverage_ranges. Never mark visuals inspected unless you actually saw their pixels.',
    inputSchema: { type: 'object', properties: { brief_id: sourceId, page_start: pageNumber, page_end: pageNumber, summary: { type: 'string', minLength: 20, maxLength: 6000 }, essential_element_ids: { type: 'array', maxItems: 64, uniqueItems: true, items: sourceId }, visual_review: { type: 'string', enum: ['inspected', 'not_needed', 'unresolved'] }, visual_notes: { type: 'string', minLength: 5, maxLength: 2000 } }, required: ['brief_id', 'page_start', 'page_end', 'summary', 'essential_element_ids', 'visual_review', 'visual_notes'], additionalProperties: false },
    execute: async (args) => {
      const brief = await getLessonBrief(String(args.brief_id))
      if (!brief || !await accessibleSource(brief.source_id)) return refusalResult(AGENT_ACCESS_REFUSAL)
      const review = await recordScopeReview(args as unknown as ScopeReviewInput)
      return textResult({ saved: true, page_start: review.page_start, page_end: review.page_end, brief_id: brief.brief_id, note: 'Checkpoint saved. Continue with the next unread packet; no readback is needed. Use get_authoring_workspace with view: reviews and this brief_id when resuming.' })
    },
  })
  useModelContextTool({ name: 'open_lesson', description: 'Open a saved lesson or its proposed plan in the visible workspace. Does not approve the plan or accept a revision.', inputSchema: { type: 'object', properties: { plan_id: sourceId }, required: ['plan_id'], additionalProperties: false },
    execute: async (args) => {
      const plan = await getLessonPlan(String(args.plan_id))
      if (!plan || !await accessibleSource(plan.source_id)) return refusalResult(AGENT_ACCESS_REFUSAL)
      const document = await getLessonDocumentByPlan(plan.plan_id)
      closeSourceInspection(); navigatePrism(document ? lessonPath(document.lesson_id) : sourcePath(plan.source_id, 'lessons', plan.plan_id))
      return textResult({ plan_id: plan.plan_id, visible_state: 'lesson_open', status: plan.status })
    },
  })
}

async function accessibleSource(id: unknown) {
  if (typeof id !== 'string') return null
  const source = (await loadLibrarySources()).find((source) => source.id === id)
  return source?.storage_location === 'browser_vault' && agentContentAllowed(source) ? source : null
}
